### ISSUE TITLE
网络连接问题

### ISSUE THREAD

**Issue by DARKTEMPLE9** [chaitin/passionfruit#11]
完全越狱的9.0iphone, npm start这步没有问题，也看到localhost的UI了，选择iphone能看到各种APP，选个APP启动一直在请求，console显示如下
  <-- GET /favicon.ico
  --> GET /favicon.ico 200 1ms 206b
An unhandledRejection occurred: 
Rejection: Error: The connection is closed
Error: The connection is closed
这是怎么回事呢，实验了不同浏览器还是一个问题。。

**Comment by ChiChou** [comment]
尝试先启动 App 再附加有没有问题？

**Comment by DARKTEMPLE9** [comment]
试了下还是同样的问题，无论系统app还是普通的。。抛出的问题还是一样的，奇怪

**Comment by ChiChou** [comment]
这是在异步任务里抛出的异常，所以在这里暂时搞不清楚哪个地方出了问题

**Comment by DARKTEMPLE9** [comment]
解决了，frida -U pid之前也不好用，是ios frida版本装错了，应该是64位而非32位。。
