### ISSUE TITLE
Unable to launch iOS app: timeout

### ISSUE THREAD

**Issue by zhangkn** [chaitin/passionfruit#12]
```
An unhandledRejection occurred: 
Rejection: Error: Unable to launch iOS app: timeout
Error: Unable to launch iOS app: timeout
```
启动应用程序失败之后，装置就重启了。这个问题 有点向[Failed to spawn: unable to launch iOS app: timeout](http://iosre.com/t/failed-to-spawn-unable-to-launch-ios-app-timeout/10422)

**Comment by ChiChou** [comment]
重启是 SpringBoard 进程崩溃了。需要 Console 的日志确认细节。

**Comment by ChiChou** [comment]
还有其他细节吗
