### ISSUE TITLE
an unhandledRejection occurred:

### ISSUE THREAD

**Issue by ismilent** [chaitin/passionfruit#13]
an unhandledRejection occurred:
Rejection: Error: GDBus.Error:re.frida.Error.InvalidArgument: Script(line 1): SyntaxError: invalid token
Error: GDBus.Error:re.frida.Error.InvalidArgument: Script(line 1): SyntaxError: invalid token

在进入general页面，会出现上面报错，General界面卡死，信息无法获取。
macos 10.13.2 frida 10.6.29

**Comment by ChiChou** [comment]
执行过 `npm run build` 吗

**Comment by ismilent** [comment]
执行过
yarn run build                                                                                                                                                             
yarn run v1.2.1
$ npm run compile && cd gui && (yarn run build || npm run build)

> Passionfruit@0.0.3 compile /Users/Smilent/Github/passionfruit
> node compile.js compile

 28% building modules 156/192 modules 36 active ...it/node_modules/es-abstract/es2016.js(node:54101) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.      

------
build能通过

**Comment by ismilent** [comment]
node v8.9.3

**Comment by ChiChou** [comment]
已修复，pull 最新的代码然后
`npm install; npm run build; npm start`
