### ISSUE TITLE
'Modules' is not working 

### ISSUE THREAD

**Issue by ShilpaRanganatha** [chaitin/passionfruit#15]
The frameworks and exported symbols are not listed for an application when '**Modules**' is selected. It keeps loading. Can you please help resolve this issue?

<img width="1315" alt="screen shot 2018-01-11 at 2 41 34 pm" src="https://user-images.githubusercontent.com/29225364/34817502-3669aad8-f6de-11e7-8672-af4d43d7342f.png">

**Comment by ChiChou** [comment]
It's a known bug after I upgraded vue.js, and solved in the latest commit. Can you try `git pull && npm install && npm run build` to see if it's gone?

**Comment by ChiChou** [comment]
Have you solved the problem?

**Comment by ShilpaRanganatha** [comment]
@ChiChou Hey... Really sorry for the delayed response. It worked for me. Thanks a lot :)
