### ISSUE TITLE
Keychain problem

### ISSUE THREAD

**Issue by r3ggi** [chaitin/passionfruit#20]
Hi!
Unfortunately Passionfruit crashes when opening keychain that has binary data.
In my case application had stored AES encrypted data in keychain and whenever i tried to open them Passionfruit was printing following error:
![error](https://user-images.githubusercontent.com/15366054/37142513-9abd3d0a-22b8-11e8-9238-0013606e96b6.png)

**Comment by ChiChou** [comment]
Thanks for reporting

**Comment by ChiChou** [comment]
I have fixed another problem in Keychain: https://github.com/chaitin/passionfruit/issues/36

Does this still exists in the latest release?
