### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by zyings** [chaitin/passionfruit#25]
when I cd in passionfruit dir,npm install, I got this problem,"npm ERR! Unexpected end of JSON input while parsing near '...,"tarball":"http://re'  npm ERR! A complete log of this run can be found in:",how can I to fix it

**Comment by zyings** [comment]
I've installed passionfruit before, I update it this morning,somehow it has some problems,so I uninstall it and then tried to install it again, problems like this happened...

**Comment by ChiChou** [comment]
Would you mind paste the full `debug.log` here?

**Comment by ChiChou** [comment]
Full path would be like

> ...
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/admin/.npm/_logs/2018-04-09T07_44_46_860Z-debug.log

**Comment by zyings** [comment]
I changed my npm version @4 and fixed this problem, thx, maybe it has some problems with npm@5
