### ISSUE TITLE
Internal Server Error with Frida 11.0.0

### ISSUE THREAD

**Issue by hduarte** [chaitin/passionfruit#29]
Passionfruit installed via npm displays "Internal Server Error". The device is running frida 11.0.0 and the computer as well. I can use all frida tools to interact with apps and device.

Please let me know if you can reproduce it.

**Comment by ChiChou** [comment]
Yes it is not compatible with frida@11. Will make a new release soon.

**Comment by hduarte** [comment]
Thks @ChiChou for the feedback

**Comment by hduarte** [comment]
Just checked and everything seems working fine. Thks.

**Comment by AsTryE** [comment]
@ChiChou frida - 11.0.1 好像不兼容了，也提示这个错误。

**Comment by ChiChou** [comment]
@AsTryE 11.0.1 实测没问题，请检查是不是最新版

**Comment by ChiChou** [comment]
@AsTryE 无论有没有问题，目前最新版都升级到 11.0.2 了

**Comment by AsTryE** [comment]
@ChiChou 嗯，感谢大佬，你这个工具很好用。现在又升级到`11.0.2`了啊，更新好快！之前调试时候，手机系统` iOS 10.1.1` 出问题了，确认了下版本，是最新版本，但是一次下班之后关了电脑，第二天来试了下，就可以了，不知道为啥。只能说`frida`确实好用，久了再用`cycript`都有点不习惯了。

**Comment by AsTryE** [comment]
我发现在控制台里注入进程，运行frida代码是有运行时方法提示的，不知道 `Code Runer` 这里可不可以做到，如果可以那就更方便了。
