### ISSUE TITLE
缺少文件

### ISSUE THREAD

**Issue by 1522402210** [chaitin/passionfruit#31]
缺少文件

InternalServerError: ENOENT: no such file or directory, stat '/Users/w/passionfruit/gui/static/build.js'

ls -l gui/
total 704
-rw-r--r--   1 w  staff     208  6 26 10:21 index.html
drwxr-xr-x   2 w  staff      68  6 26 10:33 node_modules
-rw-r--r--   1 w  staff  346249  6 26 10:21 package-lock.json
-rw-r--r--   1 w  staff    1376  6 26 10:21 package.json
drwxr-xr-x  11 w  staff     374  6 26 10:21 src
-rw-r--r--   1 w  staff    2717  6 26 10:21 webpack.config.js

没有static文件夹

**Comment by ChiChou** [comment]
RDFM

**Comment by ChiChou** [comment]
RTFM
