### ISSUE TITLE
Unable to detect device on Kali for Passion fruit.

### ISSUE THREAD

**Issue by chackokavanattu12** [chaitin/passionfruit#32]
i installed kali linux sucessfully and i am getting the passionfruit to run on port 31337, But it isnt detecting the device in vmware. kali has prompted that the iphone is connected but stil passionfruit shows " no device connected"

**Comment by ChiChou** [comment]
It's a known problem that USB devices are missing, if you use Windows or Linux inside VM. Haven't got an idea about how to fix.

**Comment by chackokavanattu12** [comment]
Also one other thing does passion fruit support Frida 12.0.3 ??

**Comment by ChiChou** [comment]
@chackokavanattu12 Not now. It has breaking changes so I need some time to check

**Comment by ChiChou** [comment]
@chackokavanattu12 FYI it has been ported to frida 12 now

**Comment by daukstsoskars** [comment]
Hi, just got the same problem. Running Kali linux and iOS device doesn't seem to be recognized by passionfruit. Does anyone know when this can potentially be fixed or any way to fix this? 

Thank you!

P.S Runs fine on my mac i would just prefer to have it on Kali as one of the tools!
