### ISSUE TITLE
After upgrading to frida 12 (both client and phone) not working anymore

### ISSUE THREAD

**Issue by B4RD4k** [chaitin/passionfruit#33]
(node:587) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.

  Error: Unable to communicate with remote frida-server; please ensure that major versions match and that the remote Frida has the feature you are trying to use

frida-ps -U working!

Please HELP!!

**Comment by ChiChou** [comment]
It's a bug. Frida 12 has some breaking change and currently I haven't adapt to it. Please wait for the new release. Thanks!

**Comment by B4RD4k** [comment]
please update here when it will be updated. 10x!!

**Comment by ChiChou** [comment]
Having trouble with network connection. Source repo has been updated but unable to publish to npm

**Comment by stevepoland85** [comment]
Is this on npm yet? Doesn't seem to work for me with Frida 12.

**Comment by ChiChou** [comment]
@stevepoland85 the latest is 0.4.10 and supports frida 12.2.16

**Comment by stevepoland85** [comment]
@ChiChou Okay, I have those versions, but my issue seems to be that I can't enumerate applications.

What device/iOS are you using for testing?
