### ISSUE TITLE
problem in keychain

### ISSUE THREAD

**Issue by iOSleep** [chaitin/passionfruit#36]
i have proble when use keychain

my device info:
iOS 11.3.1 use `electra` multipath to jailbreak iphone8plus

<img width="747" alt="wx20180830-173331 2x" src="https://user-images.githubusercontent.com/26478957/44843627-439b3480-ac7b-11e8-8be1-c4573fba9aa5.png">
<img width="664" alt="wx20180830-173310 2x" src="https://user-images.githubusercontent.com/26478957/44843632-45fd8e80-ac7b-11e8-8106-7d7799e932e7.png">

it's a great tool! thanks!

**Comment by ChiChou** [comment]
reproduced
