### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by RootToolKit** [chaitin/passionfruit#4]
npm install
npm run build
npm start
'''
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.10.10
3 info using node@v6.11.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle Passionfruit@0.0.2~prestart: Passionfruit@0.0.2
6 silly lifecycle Passionfruit@0.0.2~prestart: no script for prestart, continuing
7 info lifecycle Passionfruit@0.0.2~start: Passionfruit@0.0.2
8 verbose lifecycle Passionfruit@0.0.2~start: unsafe-perm in lifecycle true
11 silly lifecycle Passionfruit@0.0.2~start: Args: [ '-c', 'cross-env NODE_ENV=production node .' ]
12 silly lifecycle Passionfruit@0.0.2~start: Returned: code: 1  signal: null
13 info lifecycle Passionfruit@0.0.2~start: Failed to exec start script
14 verbose stack Error: Passionfruit@0.0.2 start: `cross-env NODE_ENV=production node .`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:920:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
15 verbose pkgid Passionfruit@0.0.2
16 verbose cwd /Users/XXXXXXXXXX/GitHub/passionfruit
17 error Darwin 16.7.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
19 error node v6.11.4
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error Passionfruit@0.0.2 start: `cross-env NODE_ENV=production node .`
22 error Exit status 1
23 error Failed at the Passionfruit@0.0.2 start script 'cross-env NODE_ENV=production node .'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the Passionfruit package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     cross-env NODE_ENV=production node .
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs Passionfruit
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls Passionfruit
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
'''

**Comment by ChiChou** [comment]
Your node.js version (6.11.4) seems to low to run the project, please upgrade to the latest (8.7.0) test build.
