### ISSUE TITLE
Passionfruit not finding devices on Windows

### ISSUE THREAD

**Issue by vincentcox** [chaitin/passionfruit#41]
It appears that Passionfruit cannot find my iPhone (jailbroken).

I did the usual stuff: reinstall iTunes, reinstalled PassionFruit, run PassionFruit as Administrator, tested on my Mac to exclude the possibility that the issue would be the iPhone (on Mac it works).

![image](https://user-images.githubusercontent.com/9286611/50076635-86f5c080-01e2-11e9-91d3-78178980221d.png)

Versions:
```
C:\WINDOWS\system32>node --version
v11.3.0

C:\WINDOWS\system32>npm --version
6.4.1

iOS 11.1.2(15B202)
Elektra Jailbreak
```

Any idea what could cause this?

**Comment by ChiChou** [comment]
Is your Windows a virtual machine? It is known that we have problem on VM.
Otherwise I need to patch this in upstream `frida` library

**Comment by vincentcox** [comment]
Hi, thanks for your reply.
Windows 10 is running native on my machine.

**Comment by ChiChou** [comment]
@vincentcox Thanks for the report. Will contact you later if I got time to look at this

**Comment by ChiChou** [comment]
My Windows worked smoothly. Can you `pip install frida-tools`, and check the result of `frida-ls-devices`?

**Comment by ChiChou** [comment]
I think it's fine on Windows now
