### ISSUE TITLE
Cannot interact with the device both the frida versions are same .

### ISSUE THREAD

**Issue by Soujanya2107** [chaitin/passionfruit#44]
Unable to communicate with remote frida-server; please ensure that major versions match and that the remote Frida has the feature you are trying to use

**Comment by ChiChou** [comment]
Could you paste your screenshot here?

![image](https://user-images.githubusercontent.com/2802045/51048638-7d575100-1606-11e9-894e-bde1023820ee.png)
From Passionfruit web ui

![img_052b8cf9ef92-1](https://user-images.githubusercontent.com/2802045/51048787-ea6ae680-1606-11e9-9666-21f6cc3fe864.jpeg)
on iPhone Cydia

**Comment by ChiChou** [comment]
So what exact version do you use?

**Comment by Soujanya2107** [comment]
12.2.28

**Comment by Soujanya2107** [comment]
<img width="1710" alt="screen shot 2019-01-14 at 11 12 07 am" src="https://user-images.githubusercontent.com/41462752/51097843-40997e80-17ed-11e9-9b25-e14bb02a6b68.png">

<img width="754" alt="screen shot 2019-01-14 at 11 19 25 am" src="https://user-images.githubusercontent.com/41462752/51097985-3c219580-17ee-11e9-8c22-d89c273f6235.png">

**Comment by Soujanya2107** [comment]
resolved. Thanks!!
