### ISSUE TITLE
Does not work on iOS 12.0.1

### ISSUE THREAD

**Issue by daukstsoskars** [chaitin/passionfruit#46]
Crashes when you select any application from the menu.

**Device:**
- Jailbroken iOS 12.0.1 with unc0ver jailbreak.
- CPU: A10X
- OS Build: 16A404

**Versioning:**
- Frida 12.4.0 (Both computer and ios device)
- passionfruit 0.4.12

<img width="1440" alt="screen shot 2019-02-28 at 3 42 25 pm" src="https://user-images.githubusercontent.com/37187829/53597194-8af17780-3b6f-11e9-9579-7741d4cec3cf.png">

```
listening on http://localhost:31337
  <-- GET /
  --> GET / 200 9ms 208b
  <-- GET /static/build.js
  --> GET /static/build.js 200 9ms 830.73kb
  <-- GET /static/0.build.js
  --> GET /static/0.build.js 200 1ms 52.79kb
  <-- GET /static/logo.svg?abda96cf81a18b28052a52d16b35d4e1
  --> GET /static/logo.svg?abda96cf81a18b28052a52d16b35d4e1 200 2ms 16.33kb
  <-- GET /static/MaterialIcons-Regular.woff2?570eb83859dc23dd0eec423a49e147fe
  --> GET /static/MaterialIcons-Regular.woff2?570eb83859dc23dd0eec423a49e147fe 200 0ms 43.26kb
  <-- GET /favicon.ico
  --> GET /favicon.ico 200 1ms 208b
  <-- GET /favicon.ico
  --> GET /favicon.ico 200 1ms 208b
  <-- GET /favicon.ico
  --> GET /favicon.ico 200 0ms 208b
An unhandledRejection occurred: 
Rejection: Error: Unexpected error while preparing pipe endpoints for process with pid 1 (mach_port_allocate remote_rx returned '(os/kern) invalid task')
Error: Unexpected error while preparing pipe endpoints for process with pid 1 (mach_port_allocate remote_rx returned '(os/kern) invalid task')

```

**Comment by ChiChou** [comment]
Frida does not support Unc0ver jailbreak yet. Please track this issue instead
https://github.com/frida/frida-core/issues/120#issuecomment-447981159

**Comment by ChiChou** [comment]
Now you can fetch the latest master commits from http://github.com/frida/frida and build frida-server yourself. Copy to iOS and put under `/usr/local/bin`, then `inject /usr/local/bin/frida-server; frida-server`, attaching will work. But the stability is still not ready for production. Your device may unexpectedly reboot.
