### ISSUE TITLE
iPhone SE 11.2.6 jailbroken reboots - On selecting app

### ISSUE THREAD

**Issue by nikhilgeo** [chaitin/passionfruit#47]
Device: iPhones SE 11.2.6 - Jailbroken (uncover).
Frida is installed and frida-ps -U works fine.
passionfruit list all the apps and on selecting an app my device reboots. Any idea why ?
`
passionfruit 
listening on http://localhost:31337
<-- GET /static/MaterialIcons-Regular.woff2?570eb83859dc23dd0eec423a49e147fe
  <-- GET /static/0.build.js
  <-- GET /
  <-- GET /static/logo.svg?abda96cf81a18b28052a52d16b35d4e1
  <-- GET /favicon.ico
  <-- GET /static/build.js
  --> GET / 200 9ms 208b
  --> GET /static/MaterialIcons-Regular.woff2?570eb83859dc23dd0eec423a49e147fe 200 12ms 43.26kb
  --> GET /static/logo.svg?abda96cf81a18b28052a52d16b35d4e1 200 11ms 16.33kb
  --> GET /static/0.build.js 200 11ms 52.79kb
  --> GET /favicon.ico 200 11ms 208b
  --> GET /static/build.js 200 17ms 830.73kb
  <-- GET /static/logo.svg?abda96cf81a18b28052a52d16b35d4e1
  --> GET /static/logo.svg?abda96cf81a18b28052a52d16b35d4e1 200 1ms 16.33kb
An unhandledRejection occurred: 
Rejection: Error: The connection is closed
Error: The connection is closed`

**Comment by ChiChou** [comment]
unc0ver is not supported by frida yet 
https://github.com/chaitin/passionfruit/issues/46
