### ISSUE TITLE
Cannot select phone in Passionfruit

### ISSUE THREAD

**Issue by sushi2k** [chaitin/passionfruit#49]
Hi, 

I have a rooted iPhone with iOS 10.3.3, Frida server is running (frida-server-12.5.8-ios-arm64) and I can access Frida via USB:

```bash
$ frida-ps -U | grep -i cydia
455  Cydia
```

I can also see it in Passionfruit, but when I select the iPhone nothing happens (also in an incognito windows, so cannot be a caching issue in the browser). Any ideas?

![image](https://user-images.githubusercontent.com/5951320/58416610-c3dcb200-80b4-11e9-91ce-32a521fdc859.png)

**Comment by ChiChou** [comment]
Did you see anything from the js console?

**Comment by sushi2k** [comment]
This is the output from passionfruit:

```bash
$ passionfruit
listening on http://localhost:31337
  <-- GET /
  --> GET / 200 4ms 208b
  <-- GET /static/build.js
  --> GET /static/build.js 200 4ms 830.73kb
  <-- GET /static/0.build.js
  --> GET /static/0.build.js 200 0ms 52.79kb
  <-- GET /static/logo.svg?abda96cf81a18b28052a52d16b35d4e1
  --> GET /static/logo.svg?abda96cf81a18b28052a52d16b35d4e1 200 1ms 16.33kb
  <-- GET /static/MaterialIcons-Regular.woff2?570eb83859dc23dd0eec423a49e147fe
  --> GET /static/MaterialIcons-Regular.woff2?570eb83859dc23dd0eec423a49e147fe 200 1ms 43.26kb
  <-- GET /favicon.ico
  --> GET /favicon.ico 200 1ms 208b
  <-- GET /favicon.ico
  --> GET /favicon.ico 200 1ms 208b
  <-- GET /apps/c82b85441713bbd565e058d175c5a86634b1f59c
  --> GET /apps/c82b85441713bbd565e058d175c5a86634b1f59c 200 1ms 208b
  <-- GET /static/build.js
  --> GET /static/build.js 200 5ms 830.73kb
  <-- GET /static/0.build.js
  --> GET /static/0.build.js 200 1ms 52.79kb
  <-- GET /static/logo.svg?abda96cf81a18b28052a52d16b35d4e1
  --> GET /static/logo.svg?abda96cf81a18b28052a52d16b35d4e1 200 1ms 16.33kb
  <-- GET /static/MaterialIcons-Regular.woff2?570eb83859dc23dd0eec423a49e147fe
  --> GET /static/MaterialIcons-Regular.woff2?570eb83859dc23dd0eec423a49e147fe 200 0ms 43.26kb
  <-- GET /favicon.ico
  --> GET /favicon.ico 200 1ms 208b
  <-- GET /apps/c82b85441713bbd565e058d175c5a86634b1f59c
  --> GET /apps/c82b85441713bbd565e058d175c5a86634b1f59c 200 1ms 208b
  <-- GET /static/build.js
  --> GET /static/build.js 200 4ms 830.73kb
  <-- GET /static/0.build.js
  --> GET /static/0.build.js 200 1ms 52.79kb
  <-- GET /static/logo.svg?abda96cf81a18b28052a52d16b35d4e1
  --> GET /static/logo.svg?abda96cf81a18b28052a52d16b35d4e1 200 1ms 16.33kb
  <-- GET /static/MaterialIcons-Regular.woff2?570eb83859dc23dd0eec423a49e147fe
  --> GET /static/MaterialIcons-Regular.woff2?570eb83859dc23dd0eec423a49e147fe 200 2ms 43.26kb
  <-- GET /favicon.ico
  --> GET /favicon.ico 200 0ms 208b
```

**Comment by sushi2k** [comment]
Browser Console 

![image](https://user-images.githubusercontent.com/5951320/58467332-02827300-816e-11e9-81f1-8b351ad339cb.png)

**Comment by sushi2k** [comment]
Still facing the same issue, nothing is happening after I click on "iPhone" in the browser. I tested in Chrome and Safari. I upgraded now to Frida 12.6.2 on my mac and on the iPhone. 

With objection I can connect without problems:
![image](https://user-images.githubusercontent.com/5951320/58684365-9b9dcd80-83aa-11e9-8da5-21254c6bc787.png)

Also frida-ps is working. 

```bash
$ frida-ps -U | grep -i igoat
1469  iGoat-Swift
```

Any idea what might be wrong?

**Comment by sushi2k** [comment]
I could finally fix it. When adding the Frida repo to Cydia and installing and using Frida like this, instead of copying the frida binary manually via SSH an executing it on the iOS device it works. 

I raised a ticket on Frida now, so can close this. No idea why that is actually making a difference.

**Comment by ChiChou** [comment]
Sorry, the `frida` dependency of my project has not been updated for a while. I'll try to upgrade it during the incoming vacation.

**Comment by ChiChou** [comment]
I've just upgraded `frida` yesterday.

**Comment by ChiChou** [comment]
https://github.com/frida/frida/issues/911
