### ISSUE TITLE
Error: Unable to launch iOS app: The operation couldn’t be completed. (FBSOpenApplicationErrorDomain error 1.)

### ISSUE THREAD

**Issue by vincentcox** [chaitin/passionfruit#52]
When I select an app it gives:

```
An unhandledRejection occurred: 
Rejection: Error: Unable to launch iOS app: The operation couldn’t be completed. (FBSOpenApplicationErrorDomain error 1.)
Error: Unable to launch iOS app: The operation couldn’t be completed. (FBSOpenApplicationErrorDomain error 1.)
```

I use this on Ubuntu 18.04. Any idea on how I can give you guys more information about what is going wrong?

Edit: I checked this on my mac and I have the same error.

**Comment by ChiChou** [comment]
unc0ver (iOS 12) is not supported yet.

**Comment by vincentcox** [comment]
Is electra supported?

**Comment by ChiChou** [comment]
Due to the release note of frida 12.6.7, Chimera 1.0.8 (Electra) is supported.
For unc0ver users, temporary workaround is to manually launch the app on phone, then attach to it.

**Comment by vincentcox** [comment]
How do I attach to it in passionfruit?

**Comment by ChiChou** [comment]
@vincentcox Nothing special. If the app has been running, we will attach to it instead of new process creation.
