### ISSUE TITLE
Frida can not be built

### ISSUE THREAD

**Issue by c3ntipede** [chaitin/passionfruit#53]
Hello,

I am getting timeout error, when I would like to hook apps, so I decided to update the passionfruit.

When I cloned it from github and issued the `npm install` command I got the following error:

> rebuild-install WARN install No prebuilt binaries found (target=11.6.0 runtime=node arch=x64 libc= platform=darwin)
gyp: binding.gyp not found (cwd: /Users/.../Programs/MobilePentest/iOS_tools/passionfruit/node_modules/frida) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:323:16)
gyp ERR! stack     at ChildProcess.emit (events.js:188:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Darwin 18.5.0
gyp ERR! command "/usr/local/Cellar/node/11.6.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/.../Programs/MobilePentest/iOS_tools/passionfruit/node_modules/frida
gyp ERR! node -v v11.6.0
gyp ERR! node-gyp -v v5.0.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! frida@12.6.10 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the frida@12.6.10 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

I figured it out the install process has problem with the frida building. As the error log says: "gyp: binding.gyp not found", I put the binding.gyp file from the [frida repo](https://github.com/frida/frida-node).

Then `npm install` again. Error again:

> make: *** No rule to make target `Release/obj.target/frida_binding/src/addon.o', needed by `Release/frida_binding.node'.  Stop.

OK. cc files and libraries are missing, so I cloned the frida repo into the passionfruit folder, but it still not working:

> ./src/glib_context.h:4:10: fatal error: 'frida-core.h' file not found
#include <frida-core.h>
         ^~~~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/frida_binding/src/addon.o] Error 1

I stoped here, because I hope there is a better and easier solution. Any idea what's wrong?

**Comment by ChiChou** [comment]
Uninstall node.js and use 10.16.0 LTS
