### ISSUE TITLE
Error: GDBus.Error:re.frida.Error.InvalidOperation: JIT may only be enabled before the first script is created

### ISSUE THREAD

**Issue by ShilpaRanganatha** [chaitin/passionfruit#54]
@ChiChou I am getting the message - "**Error: GDBus.Error:re.frida.Error.InvalidOperation: JIT may only be enabled before the first script is created**" everytime I click on an application from the passionfruit GUI. I updated passionfruit to 0.5.5.

Node : v10.16.0
npm : 6.9.0

**Comment by ChiChou** [comment]
What's the frida version on you iDevice?

**Comment by ShilpaRanganatha** [comment]
Frida got installed along with other packages during passionfruit installation. The version is 12.6.10

**Comment by ChiChou** [comment]
Starting from passionfruit 0.5 I upgraded the js engine to v8 and there are breaking changes
