### ISSUE TITLE
prebuild-install http 200 https://github.com/frida/frida/releases/download/12.6.18/frida-v12.6.18-node-v64-darwin-x64.tar.gz

### ISSUE THREAD

**Issue by ByboyCn** [chaitin/passionfruit#57]
在全新安装的时候，使用npm的话，会提示`/usr/local/bin/passionfruit -> /usr/local/lib/node_modules/passionfruit/bin/cli.js

> frida@12.6.18 install /usr/local/lib/node_modules/passionfruit/node_modules/frida
> prebuild-install || node-gyp rebuild

prebuild-install WARN install EACCES: permission denied, access '/Users/byboy/.npm'
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/passionfruit/node_modules/frida/build'
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/passionfruit/node_modules/frida
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! frida@12.6.18 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the frida@12.6.18 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/byboy/.npm/_logs/2019-08-28T07_41_19_393Z-debug.log
ByboydeMacBook-Pro:~ byboy$ sudo npm install --unsafe-perm=true -g passionfruit  
/usr/local/bin/passionfruit -> /usr/local/lib/node_modules/passionfruit/bin/cli.js

> frida@12.6.18 install /usr/local/lib/node_modules/passionfruit/node_modules/frida
> prebuild-install || node-gyp rebuild

^C
ByboydeMacBook-Pro:~ byboy$ node-gyp
-bash: node-gyp: command not found
ByboydeMacBook-Pro:~ byboy$ npm i -g node-gyp
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
npm ERR! path /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!  { [Error: EACCES: permission denied, access '/usr/local/lib/node_modules']
npm ERR!   stack:
npm ERR!    'Error: EACCES: permission denied, access \'/usr/local/lib/node_modules\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/byboy/.npm/_logs/2019-08-28T07_48_51_953Z-debug.log
ByboydeMacBook-Pro:~ byboy$ sudo npm i -g node-gyp
Password:
/usr/local/bin/node-gyp -> /usr/local/lib/node_modules/node-gyp/bin/node-gyp.js
+ node-gyp@5.0.3
added 98 packages from 67 contributors in 3.215s
ByboydeMacBook-Pro:~ byboy$ sudo npm install -g passionfruit 
/usr/local/bin/passionfruit -> /usr/local/lib/node_modules/passionfruit/bin/cli.js

> frida@12.6.18 install /usr/local/lib/node_modules/passionfruit/node_modules/frida
> prebuild-install || node-gyp rebuild

prebuild-install WARN install EACCES: permission denied, access '/Users/byboy/.npm'
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/passionfruit/node_modules/frida/build'
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/passionfruit/node_modules/frida
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! frida@12.6.18 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the frida@12.6.18 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/byboy/.npm/_logs/2019-08-28T07_49_48_761Z-debug.log`
说用cnpm 会卡在：
`prebuild-install http request GET https://github.com/frida/frida/releases/download/12.6.18/frida-v12.6.18-node-v64-darwin-x64.tar.gz
prebuild-install http 200 https://github.com/frida/frida/releases/download/12.6.18/frida-v12.6.18-node-v64-darwin-x64.tar.gz`
不动。。。

**Comment by ChiChou** [comment]
`permission denied, access '/usr/local/lib/node_modules'`
