### ISSUE TITLE
Bug in keychain.js

### ISSUE THREAD

**Issue by federicodotta** [chaitin/passionfruit#58]
Hi,

I found a potential bug in keychain.js.

In the method "decodeAcl" (case "osgn", line 167) there isn't a"break" instruction. At the moment, I'm testing an application in which a "osgn" entry is processed by the "decodeAd" method, that causes a crash at line 121.

Thank you for your great work! Your Frida scripts are awesome!

Have a nice day!
Federico

**Comment by ChiChou** [comment]
Working on a complete rewrite
