### ISSUE TITLE
Passionfruit app start errorr

### ISSUE THREAD

**Issue by freedoom1984** [chaitin/passionfruit#63]
[ 49%] Copying /Users/luigimarino/Desktop/Cofim-DEV 2019-11-18 21-22-58/final_file/Payload/Cofim.app/PkgInfo to device
[ 52%] CreatingStagingDirectory
[ 57%] ExtractingPackage
[ 60%] InspectingPackage
[ 60%] TakingInstallLock
[ 65%] PreflightingApplication
[ 65%] InstallingEmbeddedProfile
[ 70%] VerifyingApplication
[ 75%] CreatingContainer
[ 80%] InstallingApplication
[ 85%] PostflightingApplication
[ 90%] SandboxingApplication
[ 95%] GeneratingApplicationMap
[100%] Installed package Payload/Cofim.app
------ Debug phase ------
Starting debug of 00008020-0019306021C (D331pAP, D331pAP, uknownos, unkarch) a.k.a. 'iPhone' connected through USB...
[  0%] Looking up developer disk image
[ 95%] Developer disk image mounted successfully
2019-11-19 01:10:59.675 ios-deploy[93611:17493789] [ !! ] Error 0xe800007f: Device doesn't support wireless sync. AMDeviceStartService(device, CFSTR("com.apple.debugserver"), &gdbfd, NULL)

**Comment by freedoom1984** [comment]
I solved with ios-deploy beta ;)

**Comment by ChiChou** [comment]
Why open an ios-deploy issue here? It has nothing to do with this project
