### ISSUE TITLE
Extract IPA 

### ISSUE THREAD

**Issue by B4RD4k** [chaitin/passionfruit#65]
it is possible to extract the IPA of an app?
10x

**Comment by ChiChou** [comment]
I don't get it

**Comment by B4RD4k** [comment]
passionfruit allows to dump decrypted binary, 
i'm asking if there is an option to download the IPA?

**Comment by ChiChou** [comment]
Dumping application involves multiple process (PluginKit extensions), so this project will not add such function.

Use this https://github.com/ChiChou/bagbak

**Comment by B4RD4k** [comment]
10x
