### ISSUE TITLE
passionfruit  Uncaught RPC Error: invalid size

### ISSUE THREAD

**Issue by eseGithub** [chaitin/passionfruit#66]
passionfruit 
listening on http://localhost:31337
  <-- GET /
  <-- GET /static/0.build.js
  <-- GET /static/logo.svg?abda96cf81a18b28052a52d16b35d4e1
  <-- GET /static/MaterialIcons-Regular.woff2?570eb83859dc23dd0eec423a49e147fe
  <-- GET /static/build.js
  --> GET / 200 13ms 338b
  --> GET /static/MaterialIcons-Regular.woff2?570eb83859dc23dd0eec423a49e147fe 200 21ms 43.26kb
  --> GET /static/logo.svg?abda96cf81a18b28052a52d16b35d4e1 200 24ms 16.33kb
  --> GET /static/0.build.js 200 29ms 55.2kb
  --> GET /static/build.js 200 46ms 865.29kb
  <-- GET /static/logo.svg?abda96cf81a18b28052a52d16b35d4e1
  --> GET /static/logo.svg?abda96cf81a18b28052a52d16b35d4e1 200 4ms 16.33kb
nc localhost 51421
Uncaught RPC Error: invalid size
    at Object.checksec (/script1.js:107:26)
    at handleRpcMessage (frida/runtime/message-dispatcher.js:43:1)

**Comment by ChiChou** [comment]
Thanks for reporting. Will investigate it

**Comment by ChiChou** [comment]
Thanks for reporting. It's fixed on a private repo, which is going to be the replacement of this project.

For the migration progress, please refer to:
https://github.com/chaitin/passionfruit/issues/74
