### ISSUE TITLE
error while installing passionfruit 

### ISSUE THREAD

**Issue by i08-sec** [chaitin/passionfruit#77]
i have successfully installed npm and node

getting the below error while installing the tool:

$npm install -g passionfruit                    
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /usr/local/lib/node_modules
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!  [Error: EACCES: permission denied, access '/usr/local/lib/node_modules'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/i08/.npm/_logs/2020-09-20T03_16_58_295Z-debug.log

**Comment by ChiChou** [comment]
duplicated #76

**Comment by i08-sec** [comment]
node is running on : Node.js v12.18.3.

**Comment by i08-sec** [comment]
i fixed the above error by running : sudo chmod 777 /usr/local/lib/node_modules
 
again after installing passionfruit gives below error :


deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
/usr/local/bin/passionfruit -> /usr/local/lib/node_modules/passionfruit/bin/cli.js

> frida@12.11.16 install /usr/local/lib/node_modules/passionfruit/node_modules/frida
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=12.18.3 runtime=node arch=x64 libc= platform=darwin)
gyp: binding.gyp not found (cwd: /usr/local/lib/node_modules/passionfruit/node_modules/frida) while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/passionfruit/node_modules/frida
gyp ERR! node -v v12.18.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! frida@12.11.16 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the frida@12.11.16 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/i08/.npm/_logs/2020-09-20T17_33_53_568Z-debug.log
i08@i08-MacBook-Pro passionfruit % prebuild-install || node-gyp rebuild
zsh: command not found: prebuild-install
zsh: command not found: node-gyp

**Comment by i08-sec** [comment]
resolved !!!

**Comment by ChiChou** [comment]
did you downgrade it or retry `sudo npm install -g passionfruit`

**Comment by ChiChou** [comment]
https://github.com/ChiChou/bagbak/issues/48#issuecomment-697500861
