### ISSUE TITLE
run passionfruit with frida 14.0

### ISSUE THREAD

**Issue by wyu0hop** [chaitin/passionfruit#78]
(frida:1380): Frida-CRITICAL **: 16:18:39.033: file ../../../frida-core/lib/interfaces/session.vala: line 167: uncaught error: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “re.frida.HostSession12” on object at path /re/frida/HostSession (g-dbus-error-quark, 19)
zsh: segmentation fault  passionfruit

**Comment by ChiChou** [comment]
duplicated
